# Generated by Django 3.1.5 on 2021-01-08 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('Type', models.IntegerField(choices=[(0, 'Pedestrian'), (1, 'Trail'), (2, 'Mountain Bike'), (3, 'Mountain Bike'), (4, 'Snowshoes'), (5, 'Ski'), (6, 'Horse'), (7, 'Canoe / Kayak'), (8, 'Snorkeling')], default=0)),
                ('difficulty', models.IntegerField(choices=[(0, 'Very Easy'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Very Hard')], default=2)),
                ('distance', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('loop', models.BooleanField(default=True)),
                ('positiveElevation', models.IntegerField(default=0)),
                ('negativeElevation', models.IntegerField(default=0)),
                ('cumulativeElevation', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('previewImage', models.ImageField(default='images/no-img.png', upload_to='images/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
