# Generated by Django 3.1.5 on 2021-01-08 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdelweissApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1440), django.core.validators.MinValueValidator(0)]),
        ),
    ]
