# Generated by Django 3.1.5 on 2021-01-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdelweissApp', '0002_auto_20210108_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hike',
            old_name='previewImage',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='hike',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
