# Generated by Django 3.1.5 on 2021-01-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EdelweissApp', '0005_auto_20210108_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='thumbnail',
            field=models.ImageField(default='no-img.png', upload_to='media/hikes/'),
        ),
        migrations.CreateModel(
            name='PointsOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('published', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(default='no-img.png', upload_to='media/poi/')),
                ('hike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EdelweissApp.hike', verbose_name='Hike')),
            ],
        ),
    ]
